### ISSUE TITLE
repository.xbmchub v. 3.0.0 may have incorrect URL

### ISSUE THREAD

**Issue by Grossdm** [tvaddonsco/tva-release-repo#1]
I found two URLs for datadir/zip downloads in `repository.xbmchub-3.0.0.zip`.
The first works fine but the second, `https://github.com/tvaddonsco/tva-release-repo/raw/master/` gets a `404 error`.
Perhaps it should be `https://github.com/tvaddonsco/tva-release-repo/tree/master/`?

Thanks for all you hard work, and I really sympathize with the unjust legal crap that you are dealing with.

**Comment by tvaddonsco** [comment]
The way Kodi installs addons, it adds the addon directory and ZIP file to the end of that URL, at which point it works. It just won't work in a web browser until you add in the end part. Thanks for the kind words and support.

**Comment by Grossdm** [comment]
You are absolutely correct about the URLs.
I was familiar with the "each zip file in its own directory" system, but I had not tested it directly with the URL that I had questioned.  I have now.

If you don't mind answering a question, is this a system/policy that GitHub has for how its repositories are supposed to work - or just a quirk of Kodi?

TIA, and keep the faith with the legal B.S.
I know it can drag on endlessly - _needlessly_.

**Comment by tvaddonsco** [comment]
I think GitHub is setup like that so that directories cannot be browsed outside their interface, but not certain.
