### ISSUE TITLE
addons.xml broken

### ISSUE THREAD

**Issue by helberd** [tvaddonsco/tva-release-repo#5]
The addons.xml is broken, at line 112 is a ">" symbol missing for example and in line 115 is a ">" symbol placed wrong. This is not the only failure of this kind in this file. This causes Indigo Addoninstaller and repository errors described in your forum. I already tried to send you am message on your website but i cant receive any registration email.

**Comment by alfieoriginal** [comment]
Same here, trying to get in contact but forum registration not working with email confirmation

**Comment by tvaddonsco** [comment]
Thank you for your reports @helberd & @alfieoriginal -  we believe the error has been fixed. Please try in an hour once GitHub's cache has cleared and let us know!

**Comment by m7mdcc** [comment]
I'm still having the same issue .

**Comment by tvaddonsco** [comment]
It's definitely fixed now, closing ticket.
